name: Salesforce DevOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate Org
        run: echo "${{ secrets.SF_AUTH_URL }}" > auth.txt

      - name: Login
        run: sf org login sfdx-url --sfdx-url-file auth.txt --alias DevPOC

      # 🔥 STEP 1: BUILD ARTIFACT
      - name: Create Artifact
        run: |
          mkdir artifact
          cp -r force-app artifact/
          zip -r artifact.zip artifact

      # 🔥 STEP 2: DEPLOY ARTIFACT (NOT SOURCE)
      - name: Deploy Artifact
        run: |
          sf project deploy start --source-dir artifact/force-app --target-org DevPOC